apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: podman
  namespace: runners
spec:
  replicas: 2
  template:
    spec:
      enterprise: github
      # organization: acme
      # repository: acme/testrepo
      ephemeral: true
      image: ghcr.io/some-natalie/kubernoodles/podman:latest # change this to the version you really want!
      imagePullPolicy: IfNotPresent
      # imagePullSecrets:
      #   - name: ghcr
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      resources:
        limits:
          cpu: "4000m"
          memory: "8Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      labels:
        - dependabot
        - docker
        - podman
        - fedora
      containers:
        - name: runner
          securityContext:
            privileged: true # making this explicit, as it's implied by `dockerdWithinRunnerContainer`
      securityContext:
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: podman-autoscaling
  namespace: runners
spec:
  scaleTargetRef:
    name: podman
  minReplicas: 2
  maxReplicas: 6
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.75"
      scaleDownThreshold: "0.3"
      scaleUpFactor: "1.5"
      scaleDownFactor: "0.7"
