apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-podman
  namespace: test-runners
spec:
  replicas: 1
  template:
    spec:
      repository: some-natalie/kubernoodles
      env: []
      ephemeral: true
      image: ghcr.io/some-natalie/kubernoodles/podman:latest
      imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      resources:
        limits:
          cpu: "1000m"
          memory: "2Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      labels:
      - test-podman
      securityContext:
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
