apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-podman
  namespace: test-runners
spec:
  replicas: 1
  template:
    spec:
      repository: some-natalie/kubernoodles
      env:
        - name: DISABLE_RUNNER_UPDATE # Disables automatic runner updates
          value: "true"
      ephemeral: true
      image: ghcr.io/some-natalie/kubernoodles/podman:test
      imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      volumeMounts:
        - mountPath: /opt/statictoolcache
          name: runnertoolcache
          readOnly: true
      volumes:
        - name: runnertoolcache
          persistentVolumeClaim:
            claimName: test-tool-cache-pvc
      resources:
        limits:
          cpu: "1000m"
          memory: "2Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      labels:
        - test-podman
      containers:
        - name: runner
          securityContext:
            privileged: true # making this explicit, as it's implied by `dockerdWithinRunnerContainer`
      securityContext:
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
