---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-user
  namespace: runners
secrets:
- name: ghes-actions-deploy

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-user-full-access
  namespace: runners
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
- apiGroups: ["actions.summerwind.dev"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-user-view
  namespace: runners
subjects:
- kind: ServiceAccount
  name: deploy-user
  namespace: runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-user-full-access
