---
# Create the service account scoped to our `test-runners` namespace with a secret to use
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-deploy-user
  namespace: runners
secrets:
- name: ghe-actions-deploy

---
# Create a role for it in that namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-deploy-user-full-access
  namespace: runners
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["actions.github.com"]
  resources: ["*"]
  verbs: ["*"]

---
# Bind that service account to the role we created above
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-user-view
  namespace: runners
subjects:
- kind: ServiceAccount
  name: prod-deploy-user
  namespace: runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prod-deploy-user-full-access

---
# Create the credential for us to use for deployment
apiVersion: v1
kind: Secret
metadata:
  name: ghe-actions-deploy
  namespace: runners
  annotations:
    kubernetes.io/service-account.name: prod-deploy-user
type: kubernetes.io/service-account-token