ignored:
  - DL3041  # dnf should not pin all package versions
  - DL3008  # apt should not pin all package versions
  - DL3003  # don't use workdir, this is readable when workdir isn't created yet

trustedRegistries:
  - docker.io
  - quay.io
  - ghcr.io
