# Optional - if you need to pass info to daemon.json
# https://docs.docker.com/config/daemon/
apiVersion: v1
data:
  daemon.json: |-
    {
      "insecure-registries" : ["https://${PRIVATE_REGISTRY_URL}"]
    }
kind: ConfigMap
metadata:
  name: daemon-json
