apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: openshift-runner-autoscaler
  # Optional
  # namespace:
spec:
  maxReplicas: 6
  metrics:
  - scaleDownFactor: "0.5"
    scaleDownThreshold: "0.25"
    scaleUpFactor: "2"
    scaleUpThreshold: "0.75"
    type: PercentageRunnersBusy
  minReplicas: 2
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: openshift-runner
