apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: rootless-ubuntu-focal
  namespace: runners
spec:
  replicas: 1
  template:
    spec:
      organization: universal-exports-ltd
      # env:
      #   - name: DISABLE_RUNNER_UPDATE # Disables automatic runner updates, not yet in GHAE 3.3
      #     value: "true"
      ephemeral: true
      image: ghcr.io/some-natalie/kubernoodles/rootless-ubuntu-focal:latest # change this to the version you really want!
      imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      resources:
        limits:
          cpu: "4000m"
          memory: "8Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      labels:
        - docker
        - ubuntu
        - focal
        - ubuntu-latest # overlaps w/ hosted runners on GHEC, can use in GHES and GHAE
      containers:
        - name: runner
          securityContext:
            privileged: true # making this explicit, as it's implied by `dockerdWithinRunnerContainer`
      securityContext:
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: rootless-ubuntu-focal-autoscaling
  namespace: runners
spec:
  scaleTargetRef:
    name: ubuntu-focal
  minReplicas: 1
  maxReplicas: 3
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: "0.75"
      scaleDownThreshold: "0.3"
      scaleUpFactor: "1.5"
      scaleDownFactor: "0.7"
