apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ubuntu-focal
  namespace: runners
spec:
  replicas: 1
  template:
    spec:
      organization: universal-exports-ltd
      env:
        - name: DISABLE_RUNNER_UPDATE  # Disables automatic runner updates
          value: "true"
      ephemeral: true
      image: ghcr.io/some-natalie/kubernoodles/ubuntu-focal:latest # change this to the version you really want!
      imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      resources:
        limits:
          cpu: "4000m"
          memory: "8Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      labels:
      - docker
      - ubuntu
      - focal
      # - ubuntu-latest  # overlaps w/ hosted runners on GHEC, can use in GHES and GHAE
      securityContext:
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ubuntu-focal-autoscaling
  namespace: runners
spec:
  scaleTargetRef:
    name: ubuntu-focal
  minReplicas: 1
  maxReplicas: 3
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.3'
    scaleUpFactor: '1.5'
    scaleDownFactor: '0.7'
