apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: openshift-runner
  # Optional namesapce
  # namespace: 
spec:
  replicas: 0 # 0 for using HRA
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      containers:
      # Optional - passing in daemon.json entries via ConfigMap
      - name: docker
        resources: {}
        volumeMounts:
        - mountPath: /etc/docker/daemon.json
          name: daemon-json
          subPath: daemon.json
      dockerdContainerResources: {}
      # GitHub Runner Group
      group: OpenShift
      image: ghcr.io/ocpdude/actions-custom-runner:latest
      imagePullPolicy: Always
      # Lables to focus jobs
      labels:
      - docker,openshift
      # GitHub Org
      organization: ocpdude
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
      securityContext:
        fsGroup: 1000
      volumes:
      - configMap:
          name: daemon-json
        name: daemon-json
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: openshift-runner-autoscaler
  # Optional
  # namespace:
spec:
  maxReplicas: 6
  metrics:
  - scaleDownFactor: "0.5"
    scaleDownThreshold: "0.25"
    scaleUpFactor: "2"
    scaleUpThreshold: "0.75"
    type: PercentageRunnersBusy
  minReplicas: 2
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: openshift-runner
