name: 💼 Build image for Enterprise Server GHAS demo

on:
  workflow_dispatch:
    inputs:
      ghes-tag:
        description: "Which GHES version to tag the image with"
        type: string
        required: true

jobs:
  build:
    name: Build image for Octodemo (Enterprise Server) GHAS demo
    runs-on: ubuntu-latest # use the GitHub-hosted runner to build the image
    permissions:
      contents: read
      packages: write # for uploading the finished container

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: "images/ghes-demo.Dockerfile"
          push: true
          tags: ghcr.io/some-natalie/kubernoodles/octodemo:${{ github.event.inputs.ghes-tag }}
