name: Build and publish Ubuntu Focal runner

on:
  workflow_dispatch:  # build on demand
  release:
    types: [published]  # build on release

jobs:
  build:
    runs-on: ubuntu-latest  # use the GitHub hosted runners
    permissions:
      contents: write  # for uploading the SBOM to the release
      packages: write  # for uploading the finished container
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=$(cat ${GITHUB_EVENT_PATH} | jq -r '.release.tag_name')" >> $GITHUB_ENV

      - name: Set outputs
        id: vars
        run: echo ::set-output name=sha_short::${GITHUB_SHA::7}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          file: 'images/ubuntu-focal.Dockerfile'
          push: true
          tags: |
            ghcr.io/some-natalie/kubernoodles/ubuntu-focal:latest
            ghcr.io/some-natalie/kubernoodles/ubuntu-focal:${{ env.VERSION }}
            ghcr.io/some-natalie/kubernoodles/ubuntu-focal:${{ env.VERSION }}-${{ steps.vars.outputs.sha_short }}

      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "ghcr.io/some-natalie/kubernoodles/ubuntu-focal:latest"
          fail-build: false
          acs-report-enable: true

      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Generate SBOM for the Ubuntu Focal (20.04 LTS) runner
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/some-natalie/kubernoodles/ubuntu-focal:latest

  deploy:
    runs-on: ubuntu-latest  # use the GitHub hosted runners to deploy the self-hosted runners in GHEC
    # If using GHES or GHAE, use another deployment, such as having CentOS redeploy Ubuntu and vice versa
    environment: production
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write out the kubeconfig info
        run: | 
          echo ${{ secrets.DEPLOY_ACCOUNT }} | base64 -d > /tmp/config

      - name: Update deployment
        run: |
          kubectl apply -f deployments/ubuntu-focal.yml
        env:
          KUBECONFIG: /tmp/config

      - name: Remove kubeconfig info
        run: rm -f /tmp/config
