name: Update dependencies inside Dockerfiles

on:
  workflow_dispatch: # build on demand
  schedule:
    - cron: "27 5 * * 0" # build every Sunday at 5:27 AM UTC

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get the issue fields from the template
        uses: imjohnbo/extract-issue-template-fields@fcdd71b8add0dbd44221bcc368924a7722db96d2 # v1.0.3
        id: extract
        with:
          path: .github/ISSUE_TEMPLATE/ai-update.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue
        uses: imjohnbo/issue-bot@572eed14422c4d6ca37e870f97e7da209422f5bd # v3.4.4
        id: create-issue
        with:
          title: "${{ steps.extract.outputs.title }} for ${{ env.date }}"
          body: ${{ steps.extract.outputs.body }}
          assignees: "@copilot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
