name: 🧹 Weekly repo cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * 1" # Weekly at 22:30 UTC on Mondays

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-focal
          - rootless-ubuntu-focal
          - ubuntu-jammy
          - rootless-ubuntu-jammy
          - rootless-ubuntu-numbat
          - podman
          - ubi8
          - ubi9
          - wolfi
    steps:
      - name: Delete untagged container images older than 2 months
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: kubernoodles/${{ matrix.runner }}
          package-type: "container"
          min-versions-to-keep: 8
          delete-only-untagged-versions: "true"

  stale:
    name: Destalinate!
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues and pull requests
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 2 weeks."
          close-issue-message: "This issue was closed because it has been stalled for 2 weeks with no activity."
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          exempt-issue-labels: "epic"
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 2 weeks."
          close-pr-message: "This PR was closed because it has been stalled for 2 weeks with no activity."
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: "stale"
          exempt-pr-labels: "dependencies"

  # unused these days, commenting it out
  # clean-offline-runners:
  #   name: Delete offline self-hosted runners
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Delete offline self-hosted runners
  #       uses: some-natalie/runner-reaper@589129231ab2291c2a53210b092bc9e9d1bae414
  #       env:
  #         GITHUB_PAT: ${{ secrets.RUNNER_REAPER }}
